export const siteConfig = {
  title: 'Mechanical — Inside the Keyboard',
  tagline: 'A mechanical keyboard, opened layer by layer',
  mark: 'MEC',
  wordmark: 'Mechanical',
  badge: '60%',
  hint: 'Scroll to disassemble',
  colors: {
    background: '#0D0D0D',
    foreground: '#F5F5F5',
    primary: '#FF6B35',
    secondary: '#E2703A',
    accent: '#FF6B35',
    muted: '#1F1F1F',
  },
  hero: {
    eyebrow: 'A study in layers',
    headline: 'Mechanical',
    subtitle: 'Inside the Keyboard',
    lede:
      'Sixty-one keys. Four millimeters of travel. Scroll and the sandwich opens — keycaps, switches, plate, PCB, foam, and the case that holds them — without turning a single screw.',
  },
  chapters: [
    {
      id: 'assembled',
      at: 0,
      index: '01',
      title: 'Assembled',
      kicker: 'The closed stack',
      copy: 'A complete instrument. Case closed. Every layer stacked in working order.',
      body: 'From the outside it reads as one object: a 60% ANSI board, PBT caps, a dark chassis, and a faint ember glow under the lip. Nothing moves yet. Scroll, and the sandwich starts to come apart.',
      facts: ['61-key ANSI layout', 'Closed sandwich construction', 'USB-C at the north edge'],
    },
    {
      id: 'keycaps',
      at: 0.22,
      index: '02',
      title: 'Keycaps',
      kicker: 'The only surface you touch',
      copy: 'PBT shells over a cross stem. Legends face the light — letters, numbers, and the shift symbols that share the same key.',
      body: 'Each cap is a thin molded shell. Alphas carry a single letter; the number and punctuation rows carry two legends, unshifted below and shifted above. Orange marks the accents: Escape, Enter, and Fn. The spacebar is the only dark cap on the board.',
      facts: ['PBT · ~1.5 mm wall', 'Cherry-style dual legends', '61 caps, including spacebar'],
    },
    {
      id: 'switches',
      at: 0.4,
      index: '03',
      title: 'Switches',
      kicker: 'Four millimeters of travel',
      copy: 'Housing, cross stem, spring, pins. The mechanism under every key that actually closes the circuit.',
      body: 'An MX-style switch sits under each cap. A plastic housing holds a plus-shaped stem and a return spring; two metal pins drop through the plate into the PCB. Press, the stem travels four millimeters, the contacts meet. A steel-look plate keeps the whole grid rigid so the switches do not lean.',
      facts: ['MX footprint', '4 mm travel · 2-pin contact', 'Plate-mounted grid'],
    },
    {
      id: 'pcb',
      at: 0.62,
      index: '04',
      title: 'PCB',
      kicker: 'The nervous system',
      copy: 'A diode matrix, copper traces, and a microcontroller the size of a thumbnail.',
      body: 'The board is a 15×5 scan matrix. Traces fan from an RP2040 along the north edge; a diode at each switch lets two keys fire at once without ghosting. USB-C hangs off the top side and feeds 5V into the stack. This is the only layer that thinks.',
      facts: ['RP2040 microcontroller', '15 × 5 diode matrix', 'USB-C · 5V in'],
    },
    {
      id: 'internals',
      at: 0.8,
      index: '05',
      title: 'Internals',
      kicker: 'The quiet parts',
      copy: 'Foam, standoffs, and the chassis. Nothing here types — everything here decides how the board feels and sounds.',
      body: 'A sheet of case foam sits under the PCB to swallow ping and hollow echo. Six standoffs set the gap between plate and case so the sandwich does not rattle. The dark chassis and rubber feet are the last things you see: the instrument’s body, empty of keys.',
      facts: ['Poron-style case foam', '6 brass-look standoffs', 'Chassis · 4 rubber feet'],
    },
    {
      id: 'exploded',
      at: 0.94,
      index: '06',
      title: 'Exploded',
      kicker: 'Every layer named',
      copy: 'The keyboard, taken apart without a single screw turned. Still aligned to the same grid.',
      body: 'Keycaps, switches, plate, PCB, foam, and case hang in space, each on its own plane. This is the whole instrument read as a drawing. Scroll back and the stack reseats itself — the same sixty-one keys, closed again.',
      facts: ['6 named layers', 'No fasteners removed', 'Scroll back to reassemble'],
    },
  ],
  callouts: [
    { layer: 'keycaps', from: 0.24, to: 0.44, name: 'Keycap', note: 'PBT shell · 1.5 mm · printed legends', anchor: 'keycaps' },
    { layer: 'switches', from: 0.42, to: 0.58, name: 'MX Switch', note: 'Stem, housing, spring, 2 pins', anchor: 'switches' },
    { layer: 'plate', from: 0.5, to: 0.66, name: 'Plate', note: 'Steel-look · holds the switch grid', anchor: 'plate' },
    { layer: 'pcb', from: 0.64, to: 0.82, name: 'PCB', note: 'RP2040 · 15×5 diode matrix', anchor: 'pcb' },
    { layer: 'internals', from: 0.78, to: 0.96, name: 'Chassis', note: 'Foam, standoffs, and the case', anchor: 'internals' },
  ],
  colophon: {
    title: 'Mechanical — Inside the Keyboard',
    fine: 'Keycaps · Switches · Plate · PCB · Foam · Case',
    note: 'A teardown you can scroll. Scroll back to reseat the stack.',
  },
}
